### ISSUE TITLE
No longer produces results

### ISSUE THREAD

**Issue by 503Dev** [fcannizzaro/cerebro-thingiverse#1]
Expected: Results to load when a term is entered after "thing"

Actual: Briefly the search thingiverse phrase appears and then nothing. Developer tools not show any error and it does show the plugin loading correctly.

**Comment by fcannizzaro** [comment]
@503Dev Thanks 👍 (1.0.3 fixed the issue)

**Comment by 503Dev** [comment]
Thank you.
